In [1]:
import pandas as pd
from itertools import permutations, combinations, product

Bring in our predictions

In [32]:
df_pred = pd.read_csv('/Users/tamraheberling/Documents/data_ml/MarchMadness/data/2022/predictions/phase2_submissions_xg.csv')
df_pred.head()

               ID      Pred
0  2022_1103_1104  0.159308
1  2022_1103_1112  0.064552
2  2022_1103_1116  0.182135
3  2022_1103_1120  0.061031
4  2022_1103_1124  0.092754

Excellent, now we have our submission file into a dataframe with ID and Predictions. From here we'll need to bring in the first round teams and see who we predict will win.

In [20]:
#read in the team data
df_teams = pd.read_csv('/Users/tamraheberling/Documents/data_ml/MarchMadness2023/data/raw/MTeams.csv')
df_teams.head()

   TeamID     TeamName  FirstD1Season  LastD1Season
0    1101  Abilene Chr           2014          2023
1    1102    Air Force           1985          2023
2    1103        Akron           1985          2023
3    1104      Alabama           1985          2023
4    1105  Alabama A&M           2000          2023

In [21]:
#read in the tournament slot data
df_slots = pd.read_csv('/Users/tamraheberling/Documents/data_ml/MarchMadness2023/data/raw/MNCAATourneySlots.csv')
df_slots.head()

   Season  Slot StrongSeed WeakSeed
0    1985  R1W1        W01      W16
1    1985  R1W2        W02      W15
2    1985  R1W3        W03      W14
3    1985  R1W4        W04      W13
4    1985  R1W5        W05      W12

In [22]:
df_slots_thisyear = df_slots[df_slots['Season']==2022]
df_slots_thisyear = df_slots_thisyear.reset_index(drop=True)
df_slots_thisyear.head(48)

    Season  Slot StrongSeed WeakSeed
0     2022  R1W1        W01      W16
1     2022  R1W2        W02      W15
2     2022  R1W3        W03      W14
3     2022  R1W4        W04      W13
4     2022  R1W5        W05      W12
5     2022  R1W6        W06      W11
6     2022  R1W7        W07      W10
7     2022  R1W8        W08      W09
8     2022  R1X1        X01      X16
9     2022  R1X2        X02      X15
10    2022  R1X3        X03      X14
11    2022  R1X4        X04      X13
12    2022  R1X5        X05      X12
13    2022  R1X6        X06      X11
14    2022  R1X7        X07      X10
15    2022  R1X8        X08      X09
16    2022  R1Y1        Y01      Y16
17    2022  R1Y2        Y02      Y15
18    2022  R1Y3        Y03      Y14
19    2022  R1Y4        Y04      Y13
20    2022  R1Y5        Y05      Y12
21    2022  R1Y6        Y06      Y11
22    2022  R1Y7        Y07      Y10
23    2022  R1Y8        Y08      Y09
24    2022  R1Z1        Z01      Z16
25    2022  R1Z2        Z02      Z15
26    2022  R1Z3        Z03      Z14
27    2022  R1Z4        Z04      Z13
28    2022  R1Z5        Z05      Z12
29    2022  R1Z6        Z06      Z11
30    2022  R1Z7        Z07      Z10
31    2022  R1Z8        Z08      Z09
32    2022  R2W1       R1W1     R1W8
33    2022  R2W2       R1W2     R1W7
34    2022  R2W3       R1W3     R1W6
35    2022  R2W4       R1W4     R1W5
36    2022  R2X1       R1X1     R1X8
37    2022  R2X2       R1X2     R1X7
38    2022  R2X3       R1X3     R1X6
39    2022  R2X4       R1X4     R1X5
40    2022  R2Y1       R1Y1     R1Y8
41    2022  R2Y2       R1Y2     R1Y7
42    2022  R2Y3       R1Y3     R1Y6
43    2022  R2Y4       R1Y4     R1Y5
44    2022  R2Z1       R1Z1     R1Z8
45    2022  R2Z2       R1Z2     R1Z7
46    2022  R2Z3       R1Z3     R1Z6
47    2022  R2Z4       R1Z4     R1Z5

In [23]:
#read in the tournament seed data data
df_seeds = pd.read_csv('/Users/tamraheberling/Documents/data_ml/MarchMadness2023/data/raw/MNCAATourneySeeds.csv')
df_seeds.head()

   Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228
3    1985  W04    1260
4    1985  W05    1374

In [24]:
df_seeds_thisyear = df_seeds[df_seeds['Season']==2022]
df_seeds_thisyear = df_seeds_thisyear.reset_index(drop=True)
df_seeds_thisyear.head(20)

    Season  Seed  TeamID
0     2022   W01    1124
1     2022   W02    1246
2     2022   W03    1345
3     2022   W04    1417
4     2022   W05    1388
5     2022   W06    1400
6     2022   W07    1293
7     2022   W08    1314
8     2022   W09    1266
9     2022   W10    1362
10    2022   W11    1439
11    2022  W12a    1231
12    2022  W12b    1461
13    2022   W13    1103
14    2022   W14    1463
15    2022   W15    1389
16    2022   W16    1313
17    2022   X01    1211
18    2022   X02    1181
19    2022   X03    1403

Eliminate the letters for the playin games

In [25]:
df_seeds_thisyear.Seed.replace(['W12a','Y16a','X11a','Z16a'],['W12','Y16','X11','Z16'],inplace=True)
vals_to_drop=['W12b','X11b','Y16b','Z16b']
df_seeds_thisyear = df_seeds_thisyear[df_seeds_thisyear.Seed.isin(vals_to_drop) == False]

In [26]:
print(df_seeds_thisyear[32:64])

    Season Seed  TeamID
34    2022  Y01    1242
35    2022  Y02    1120
36    2022  Y03    1458
37    2022  Y04    1344
38    2022  Y05    1234
39    2022  Y06    1261
40    2022  Y07    1425
41    2022  Y08    1361
42    2022  Y09    1166
43    2022  Y10    1274
44    2022  Y11    1235
45    2022  Y12    1350
46    2022  Y13    1355
47    2022  Y14    1159
48    2022  Y15    1240
49    2022  Y16    1394
51    2022  Z01    1112
52    2022  Z02    1437
53    2022  Z03    1397
54    2022  Z04    1228
55    2022  Z05    1222
56    2022  Z06    1161
57    2022  Z07    1326
58    2022  Z08    1371
59    2022  Z09    1395
60    2022  Z10    1260
61    2022  Z11    1276
62    2022  Z12    1412
63    2022  Z13    1151
64    2022  Z14    1255
65    2022  Z15    1174
66    2022  Z16    1136

I think with these three dataframes, we can write a function that will take the slot information to find out which slots play eachother in each round. Then we use the seed data frame to look up which TeamID is associated with the slots. Then we look at our predictions to find out who we predicted to win. From there we should be able to label the winning teams with their seed for the next round and continue on.

In [27]:
'''Given two integers 0,8 for W round 1, return a list of Strong Seeds and a list of Weak Seeds'''
def match_upID(int1:int,int2:int):
    StrongSeed = df_slots_thisyear.StrongSeed[int1:int2]
    WeakSeed = df_slots_thisyear.WeakSeed[int1:int2]
    TeamID_Strong = [int(df_seeds_thisyear.TeamID[df_seeds_thisyear.Seed==seed]) for seed in StrongSeed]
    TeamID_Weak = [int(df_seeds_thisyear.TeamID[df_seeds_thisyear.Seed==seed]) for seed in WeakSeed]
    return TeamID_Strong,TeamID_Weak

In [88]:
'''Given the TeamID of the strong and weak seed in the match up, which TeamName 
was predicted to be the winner''' 
def winners(strong:int,weak:int):
    if strong > weak:
        id_pred = '2022_'+str(weak)+'_'+str(strong)
        pred = float(df_pred.Pred[df_pred.ID==id_pred])
        print(pred)
        weak_win_prob = pred
        strong_win_prob = 1-pred
        if pred < 0.5:
            win_teamID = strong
            win_team = df_teams.loc[df_teams.TeamID == win_teamID,'TeamName'].iloc[0]
            print('winner '+win_team)
        elif pred > 0.5:
            win_teamID = weak
            win_team = df_teams.loc[df_teams.TeamID == win_teamID,'TeamName'].iloc[0]
            print('winner '+win_team)
    elif strong < weak:
        id_pred = '2022_'+str(strong)+'_'+str(weak)
        pred = float(df_pred.Pred[df_pred.ID==id_pred])
        print(pred)
        strong_win_prob = pred
        weak_win_prob = 1-pred
        if pred < 0.5:
            win_teamID = weak
            win_team = df_teams.loc[df_teams.TeamID == win_teamID,'TeamName'].iloc[0]
            print('winner '+win_team)
        elif pred > 0.5:
            win_teamID = strong
            win_team = df_teams.loc[df_teams.TeamID == win_teamID,'TeamName'].iloc[0]
            print('winner '+win_team)
    return win_team, strong_win_prob, weak_win_prob

In [89]:
'''Take the list of Strong TeamIDs and Weak TeamIDs, and use the winners function 
to make a dictionary of the winning team and the rank for the next round.'''
def round_winners(strong_teams:list, weak_teams:list, end_rank:str):
    rank = [end_rank+'{}'.format(i+1) for i in range(8)]
    winning_teams = []
    strong_win_probs = []
    weak_win_probs = []
    for i in range(len(strong_teams)):
        strong_id = strong_teams[i]
        weak_id = weak_teams[i]
        winner,strong_win_prob,weak_win_prob = winners(strong_id, weak_id)
        winning_teams.append(str(winner))
        strong_win_probs.append(strong_win_prob)
        weak_win_probs.append(weak_win_prob)
    round_wins = dict(zip(winning_teams,rank))
    return round_wins, strong_win_probs, weak_win_probs

In [114]:
'''Make a disctionary of the rank of each team and the probability that they win the round'''
def prob_win(strong_pred, weak_pred):
    round1_rank = [i+1 for i in range(16)]
    weak_pred = list(reversed(weak_pred))
    pred_list = strong_pred+weak_pred
    rank_prob = dict(zip(round1_rank,pred_list))
    return rank_prob

# Region: W
# Round: 1

In [43]:
TeamID_Strong, TeamID_Weak = match_upID(0,8)
TeamID_Strong, TeamID_Weak

([1124, 1246, 1345, 1417, 1388, 1400, 1293, 1314],
 [1313, 1389, 1463, 1103, 1231, 1439, 1362, 1266])

In [115]:
round1_w,strong_pred,weak_pred = round_winners(TeamID_Strong,TeamID_Weak,'R1W')
round1_w

0.92234504
winner Baylor
0.8724796
winner Kentucky
0.89320433
winner Purdue
0.113508396
winner UCLA
0.41570774
winner St Mary's CA
0.74389285
winner Texas
0.51378846
winner Murray St
0.54290676
winner Marquette

{'Baylor': 'R1W1',
 'Kentucky': 'R1W2',
 'Purdue': 'R1W3',
 'UCLA': 'R1W4',
 "St Mary's CA": 'R1W5',
 'Texas': 'R1W6',
 'Murray St': 'R1W7',
 'Marquette': 'R1W8'}

In [149]:
round1_prob_by_rank = prob_win(strong_pred, weak_pred)
round1_prob_by_rank

{1: 0.92234504,
 2: 0.8724796,
 3: 0.89320433,
 4: 0.886491604,
 5: 0.58429226,
 6: 0.74389285,
 7: 0.51378846,
 8: 0.45709323999999996,
 9: 0.54290676,
 10: 0.48621154,
 11: 0.25610714999999995,
 12: 0.41570774,
 13: 0.113508396,
 14: 0.10679567000000001,
 15: 0.12752039999999998,
 16: 0.07765496000000005}

In [150]:
'''function to calculate all the possible round 1 results and their probabilities'''
def round1_results(round1_prob_by_rank):
    #calculate all possible combinations of ranks from round 1 as a list of tuples
    round1_matchups = [[1,16],[2,15],[3,14],[4,13],[5,12],[6,11],[7,10],[8,9]]
    possible_combos = list(product(*round1_matchups))
    #use dict to pull the probability that each team in the tuple wins and multiply together to calculate the probability of that tuple
    probability_of_combos = []
    for i in possible_combos:
        prob_combo = 1
        for j in i:
            prob_j = round_1_prob_by_rank[j]
            prob_combo = prob_combo*prob_j
        probability_of_combos.append(prob_combo)
    round1_results_dict = dict(zip(possible_combos,probability_of_combos))
    return(round1_results_dict)

In [151]:
round1_results_pred = round1_results(round1_prob_by_rank)
round1_results_pred

{(1, 2, 3, 4, 5, 6, 7, 8): 0.06504348555154586,
 (1, 2, 3, 4, 5, 6, 7, 9): 0.07725458376915963,
 (1, 2, 3, 4, 5, 6, 10, 8): 0.06155236199151859,
 (1, 2, 3, 4, 5, 6, 10, 9): 0.07310804556891393,
 (1, 2, 3, 4, 5, 11, 7, 8): 0.022393146688629403,
 (1, 2, 3, 4, 5, 11, 7, 9): 0.0265971789802197,
 (1, 2, 3, 4, 5, 11, 10, 8): 0.021191223985303993,
 (1, 2, 3, 4, 5, 11, 10, 9): 0.02516961037160751,
 (1, 2, 3, 4, 12, 6, 7, 8): 0.04627663625110452,
 (1, 2, 3, 4, 12, 6, 7, 9): 0.05496449400736206,
 (1, 2, 3, 4, 12, 6, 10, 8): 0.04379279865038105,
 (1, 2, 3, 4, 12, 6, 10, 9): 0.05201434706540563,
 (1, 2, 3, 4, 12, 11, 7, 8): 0.015932102885324224,
 (1, 2, 3, 4, 12, 11, 7, 9): 0.018923155278905517,
 (1, 2, 3, 4, 12, 11, 10, 8): 0.015076968212388294,
 (1, 2, 3, 4, 12, 11, 10, 9): 0.017907479801737434,
 (1, 2, 3, 13, 5, 6, 7, 8): 0.008328315442460914,
 (1, 2, 3, 13, 5, 6, 7, 9): 0.009891852159363421,
 (1, 2, 3, 13, 5, 6, 10, 8): 0.007881304062151772,
 (1, 2, 3, 13, 5, 6, 10, 9): 0.009360920001699562,
 (1, 2, 3, 13, 5, 11, 7, 8): 0.0028672693013108725,
 (1, 2, 3, 13, 5, 11, 7, 9): 0.0034055631328569853,
 (1, 2, 3, 13, 5, 11, 10, 8): 0.0027133723917915228,
 (1, 2, 3, 13, 5, 11, 10, 9): 0.0032227740097424905,
 (1, 2, 3, 13, 12, 6, 7, 8): 0.00592536548506141,
 (1, 2, 3, 13, 12, 6, 7, 9): 0.007037778500750784,
 (1, 2, 3, 13, 12, 6, 10, 8): 0.005607329284029763,
 (1, 2, 3, 13, 12, 6, 10, 9): 0.006660034993835653,
 (1, 2, 3, 13, 12, 11, 7, 8): 0.0020399825957292702,
 (1, 2, 3, 13, 12, 11, 7, 9): 0.0024229637294652796,
 (1, 2, 3, 13, 12, 11, 10, 8): 0.0019304892123165357,
 (1, 2, 3, 13, 12, 11, 10, 9): 0.002292914337288652,
 (1, 2, 14, 4, 5, 6, 7, 8): 0.007776902087580187,
 (1, 2, 14, 4, 5, 6, 7, 9): 0.009236917866484737,
 (1, 2, 14, 4, 5, 6, 10, 8): 0.007359487094030054,
 (1, 2, 14, 4, 5, 6, 10, 9): 0.00874113844580522,
 (1, 2, 14, 4, 5, 11, 7, 8): 0.0026774289193386,
 (1, 2, 14, 4, 5, 11, 7, 9): 0.003180082601371267,
 (1, 2, 14, 4, 5, 11, 10, 8): 0.002533721442696779,
 (1, 2, 14, 4, 5, 11, 10, 9): 0.0030093958492955057,
 (1, 2, 14, 4, 12, 6, 7, 8): 0.005533050174289901,
 (1, 2, 14, 4, 12, 6, 7, 9): 0.006571810913329557,
 (1, 2, 14, 4, 12, 6, 10, 8): 0.005236070981700838,
 (1, 2, 14, 4, 12, 6, 10, 9): 0.006219077603959362,
 (1, 2, 14, 4, 12, 11, 7, 8): 0.0019049164284135672,
 (1, 2, 14, 4, 12, 11, 7, 9): 0.002262540584106608,
 (1, 2, 14, 4, 12, 11, 10, 8): 0.0018026725439303564,
 (1, 2, 14, 4, 12, 11, 10, 9): 0.0021411016933135735,
 (1, 2, 14, 13, 5, 6, 7, 8): 0.0009957721853508703,
 (1, 2, 14, 13, 5, 6, 7, 9): 0.0011827159177566497,
 (1, 2, 14, 13, 5, 6, 10, 8): 0.0009423254226624943,
 (1, 2, 14, 13, 5, 6, 10, 9): 0.0011192351960473655,
 (1, 2, 14, 13, 5, 11, 7, 8): 0.00034282407263288396,
 (1, 2, 14, 13, 5, 11, 7, 9): 0.00040718499036022444,
 (1, 2, 14, 13, 5, 11, 10, 8): 0.00032442344132039555,
 (1, 2, 14, 13, 5, 11, 10, 9): 0.00038532987141815114,
 (1, 2, 14, 13, 12, 6, 7, 8): 0.0007084642961504769,
 (1, 2, 14, 13, 12, 6, 7, 9): 0.0008414695776265165,
 (1, 2, 14, 13, 12, 6, 10, 8): 0.0006704384066281664,
 (1, 2, 14, 13, 12, 6, 10, 9): 0.0007963048045122269,
 (1, 2, 14, 13, 12, 11, 7, 8): 0.00024390982083488848,
 (1, 2, 14, 13, 12, 11, 7, 9): 0.0002897008290073374,
 (1, 2, 14, 13, 12, 11, 10, 8): 0.00023081828192337208,
 (1, 2, 14, 13, 12, 11, 10, 9): 0.00027415151794365746,
 (1, 15, 3, 4, 5, 6, 7, 8): 0.009506665021081695,
 (1, 15, 3, 4, 5, 6, 7, 9): 0.011291422084913781,
 (1, 15, 3, 4, 5, 6, 10, 8): 0.008996407276574999,
 (1, 15, 3, 4, 5, 6, 10, 9): 0.010685369851817885,
 (1, 15, 3, 4, 5, 11, 7, 8): 0.0032729510500792178,
 (1, 15, 3, 4, 5, 11, 7, 9): 0.003887406539280927,
 (1, 15, 3, 4, 5, 11, 10, 8): 0.0030972797061335974,
 (1, 15, 3, 4, 5, 11, 10, 9): 0.0036787551049119512,
 (1, 15, 3, 4, 12, 6, 7, 8): 0.006763728533475563,
 (1, 15, 3, 4, 12, 6, 7, 9): 0.00803353369135096,
 (1, 15, 3, 4, 12, 6, 10, 8): 0.006400694298200266,
 (1, 15, 3, 4, 12, 6, 10, 9): 0.007602344333918351,
 (1, 15, 3, 4, 12, 11, 7, 8): 0.00232861391003033,
 (1, 15, 3, 4, 12, 11, 7, 9): 0.0027657819511518007,
 (1, 15, 3, 4, 12, 11, 10, 8): 0.0022036286203494493,
 (1, 15, 3, 4, 12, 11, 10, 9): 0.002617332241704537,
 (1, 15, 3, 13, 5, 6, 7, 8): 0.001217254955358031,
 (1, 15, 3, 13, 5, 6, 7, 9): 0.0014457792985679975,
 (1, 15, 3, 13, 5, 6, 10, 8): 0.001151920396221549,
 (1, 15, 3, 13, 5, 6, 10, 9): 0.0013681789958008513,
 (1, 15, 3, 13, 5, 11, 7, 8): 0.00041907607720671395,
 (1, 15, 3, 13, 5, 11, 7, 9): 0.0004977523519486024,
 (1, 15, 3, 13, 5, 11, 10, 8): 0.00039658271981397804,
 (1, 15, 3, 13, 5, 11, 10, 9): 0.00047103614896206884,
 (1, 15, 3, 13, 12, 6, 7, 8): 0.0008660431450789505,
 (1, 15, 3, 13, 12, 6, 7, 9): 0.0010286318780715791,
 (1, 15, 3, 13, 12, 6, 10, 8): 0.0008195594180439163,
 (1, 15, 3, 13, 12, 6, 10, 9): 0.0009734214145842721,
 (1, 15, 3, 13, 12, 11, 7, 8): 0.000298161007547265,
 (1, 15, 3, 13, 12, 11, 7, 9): 0.00035413699525685665,
 (1, 15, 3, 13, 12, 11, 10, 8): 0.0002821576075249089,
 (1, 15, 3, 13, 12, 11, 10, 9): 0.0003351291576981098,
 (1, 15, 14, 4, 5, 6, 7, 8): 0.00113666114940574,
 (1, 15, 14, 4, 5, 6, 7, 9): 0.0013500550168752143,
 (1, 15, 14, 4, 5, 6, 10, 8): 0.0010756523568293745,
 (1, 15, 14, 4, 5, 6, 10, 9): 0.0012775925890581969,
 (1, 15, 14, 4, 5, 11, 7, 8): 0.0003913292720719498,
 (1, 15, 14, 4, 5, 11, 7, 9): 0.00046479643232908194,
 (1, 15, 14, 4, 5, 11, 10, 8): 0.0003703251879600054,
 (1, 15, 14, 4, 5, 11, 10, 9): 0.0004398490949937426,
 (1, 15, 14, 4, 12, 6, 7, 8): 0.0008087028870881542,
 (1, 15, 14, 4, 12, 6, 7, 9): 0.000960526706174162,
 (1, 15, 14, 4, 12, 6, 10, 8): 0.0007652968230029487,
 (1, 15, 14, 4, 12, 6, 10, 9): 0.0009089716982356257,
 (1, 15, 14, 4, 12, 11, 7, 8): 0.00027841992513964736,
 (1, 15, 14, 4, 12, 11, 7, 9): 0.0003306897723471223,
 (1, 15, 14, 4, 12, 11, 10, 8): 0.0002634761017575845,
 (1, 15, 14, 4, 12, 11, 10, 9): 0.00031294043364684315,
 (1, 15, 14, 13, 5, 6, 7, 8): 0.00014554067210834168,
 (1, 15, 14, 13, 5, 6, 7, 9): 0.00017286410698736689,
 (1, 15, 14, 13, 5, 6, 10, 8): 0.0001377289679072042,
 (1, 15, 14, 13, 5, 6, 10, 9): 0.0001635858533472169,
 (1, 15, 14, 13, 5, 11, 7, 8): 5.010668773433145e-05,
 (1, 15, 14, 13, 5, 11, 7, 9): 5.951358959536928e-05,
 (1, 15, 14, 13, 5, 11, 10, 8): 4.7417277156455416e-05,
 (1, 15, 14, 13, 5, 11, 10, 9): 5.6319275929421375e-05,
 (1, 15, 14, 13, 12, 6, 7, 8): 0.00010354815222135539,
 (1, 15, 14, 13, 12, 6, 7, 9): 0.00012298801843248187,
 (1, 15, 14, 13, 12, 6, 10, 8): 9.799034130836574e-05,
 (1, 15, 14, 13, 12, 6, 10, 9): 0.00011638679826247051,
 (1, 15, 14, 13, 12, 11, 7, 8): 3.5649518816019657e-05,
 (1, 15, 14, 13, 12, 11, 7, 9): 4.234226862765302e-05,
 (1, 15, 14, 13, 12, 11, 10, 8): 3.3736077769819695e-05,
 (1, 15, 14, 13, 12, 11, 10, 9): 4.006960303574132e-05,
 (16, 2, 3, 4, 5, 6, 7, 8): 0.005476203643666666,
 (16, 2, 3, 4, 5, 6, 7, 9): 0.006504292159917449,
 (16, 2, 3, 4, 5, 6, 10, 8): 0.005182275613860189,
 (16, 2, 3, 4, 5, 6, 10, 9): 0.006155182830854919,
 (16, 2, 3, 4, 5, 11, 7, 8): 0.0018853453262779516,
 (16, 2, 3, 4, 5, 11, 7, 9): 0.0022392952531319556,
 (16, 2, 3, 4, 5, 11, 10, 8): 0.0017841518949674449,
 (16, 2, 3, 4, 5, 11, 10, 9): 0.002119104024913245,
 (16, 2, 3, 4, 12, 6, 7, 8): 0.0038961670320404986,
 (16, 2, 3, 4, 12, 6, 7, 9): 0.004627623501463123,
 (16, 2, 3, 4, 12, 6, 10, 8): 0.003687045389741996,
 (16, 2, 3, 4, 12, 6, 10, 9): 0.004379241894974786,
 (16, 2, 3, 4, 12, 11, 7, 8): 0.0013413709171957364,
 (16, 2, 3, 4, 12, 11, 7, 9): 0.0015931964747782437,
 (16, 2, 3, 4, 12, 11, 10, 8): 0.0012693745970101223,
 (16, 2, 3, 4, 12, 11, 10, 9): 0.001507683748919742,
 (16, 2, 3, 13, 5, 6, 7, 8): 0.0007011855374119919,
 (16, 2, 3, 13, 5, 6, 7, 9): 0.0008328243232719945,
 (16, 2, 3, 13, 5, 6, 10, 8): 0.0006635503256939874,
 (16, 2, 3, 13, 5, 6, 10, 9): 0.0007881235728173699,
 (16, 2, 3, 13, 5, 11, 7, 8): 0.00024140389252000954,
 (16, 2, 3, 13, 5, 11, 7, 9): 0.00028672444409684694,
 (16, 2, 3, 13, 5, 11, 10, 8): 0.00022844685601570018,
 (16, 2, 3, 13, 5, 11, 10, 9): 0.00027133488657953096,
 (16, 2, 3, 13, 12, 6, 7, 8): 0.0004988740653148898,
 (16, 2, 3, 13, 12, 6, 7, 9): 0.0005925314109833154,
 (16, 2, 3, 13, 12, 6, 10, 8): 0.00047209765583838375,
 (16, 2, 3, 13, 12, 6, 10, 9): 0.0005607280666299333,
 (16, 2, 3, 13, 12, 11, 7, 8): 0.00017175217516435362,
 (16, 2, 3, 13, 12, 11, 7, 9): 0.0002039964908285052,
 (16, 2, 3, 13, 12, 11, 10, 8): 0.00016253360300270297,
 (16, 2, 3, 13, 12, 11, 10, 9): 0.0001930472474222628,
 (16, 2, 14, 4, 5, 6, 7, 8): 0.000654760414318438,
 (16, 2, 14, 4, 5, 6, 7, 9): 0.0007776834658807924,
 (16, 2, 14, 4, 5, 6, 10, 8): 0.0006196170100371771,
 (16, 2, 14, 4, 5, 6, 10, 9): 0.0007359423284408479,
 (16, 2, 14, 4, 5, 11, 7, 8): 0.0002254206686405365,
 (16, 2, 14, 4, 5, 11, 7, 9): 0.0002677405704986302,
 (16, 2, 14, 4, 5, 11, 10, 8): 0.00021332151066130397,
 (16, 2, 14, 4, 5, 11, 10, 9): 0.00025336994743443156,
 (16, 2, 14, 4, 12, 6, 7, 8): 0.000465843877647432,
 (16, 2, 14, 4, 12, 6, 7, 9): 0.0005533002200588304,
 (16, 2, 14, 4, 12, 6, 10, 8): 0.00044084032006193655,
 (16, 2, 14, 4, 12, 6, 10, 9): 0.0005236025582924591,
 (16, 2, 14, 4, 12, 11, 7, 8): 0.00016038055460437946,
 (16, 2, 14, 4, 12, 11, 7, 9): 0.0001904899912045664,
 (16, 2, 14, 4, 12, 11, 10, 8): 0.000151772339223519,
 (16, 2, 14, 4, 12, 11, 10, 9): 0.0001802656914056783,
 (16, 2, 14, 13, 5, 6, 7, 8): 8.383700878635881e-05,
 (16, 2, 14, 13, 5, 6, 7, 9): 9.957635516179064e-05,
 (16, 2, 14, 13, 5, 6, 10, 8): 7.933716757867441e-05,
 (16, 2, 14, 13, 5, 6, 10, 9): 9.423172523337945e-05,
 (16, 2, 14, 13, 5, 11, 7, 8): 2.8863373784005736e-05,
 (16, 2, 14, 13, 5, 11, 7, 9): 3.4282110021455354e-05,
 (16, 2, 14, 13, 5, 11, 10, 8): 2.7314170149164225e-05,
 (16, 2, 14, 13, 5, 11, 10, 9): 3.2442062844271046e-05,
 (16, 2, 14, 13, 12, 6, 7, 8): 5.964770687008136e-05,
 (16, 2, 14, 13, 12, 6, 7, 9): 7.084581534888947e-05,
 (16, 2, 14, 13, 12, 6, 10, 8): 5.6446194635766706e-05,
 (16, 2, 14, 13, 12, 6, 10, 9): 6.704325936658676e-05,
 (16, 2, 14, 13, 12, 11, 7, 8): 2.053549003802356e-05,
 (16, 2, 14, 13, 12, 11, 7, 9): 2.4390770604167434e-05,
 (16, 2, 14, 13, 12, 11, 10, 8): 1.943327461275034e-05,
 (16, 2, 14, 13, 12, 11, 10, 9): 2.3081628063890302e-05,
 (16, 15, 3, 4, 5, 6, 7, 8): 0.0008003942775531148,
 (16, 15, 3, 4, 5, 6, 7, 9): 0.0009506582594590599,
 (16, 15, 3, 4, 5, 6, 10, 8): 0.0007574341671595491,
 (16, 15, 3, 4, 5, 6, 10, 9): 0.0008996329274217428,
 (16, 15, 3, 4, 5, 11, 7, 8): 0.00027555944018071575,
 (16, 15, 3, 4, 5, 11, 7, 9): 0.0003272922672317933,
 (16, 15, 3, 4, 5, 11, 10, 8): 0.0002607691495675159,
 (16, 15, 3, 4, 5, 11, 10, 9): 0.00030972528515113345,
 (16, 15, 3, 4, 12, 6, 7, 8): 0.0005694583327708946,
 (16, 15, 3, 4, 12, 6, 7, 9): 0.0006763669889312916,
 (16, 15, 3, 4, 12, 6, 10, 8): 0.0005388934055513218,
 (16, 15, 3, 4, 12, 6, 10, 9): 0.0006400638801685936,
 (16, 15, 3, 4, 12, 11, 7, 8): 0.00019605290015854482,
 (16, 15, 3, 4, 12, 11, 7, 9): 0.00023285937200401188,
 (16, 15, 3, 4, 12, 11, 10, 8): 0.00018553001853632975,
 (16, 15, 3, 4, 12, 11, 10, 9): 0.00022036095140304143,
 (16, 15, 3, 13, 5, 6, 7, 8): 0.00010248429900824288,
 (16, 15, 3, 13, 5, 6, 7, 9): 0.00012172444012831249,
 (16, 15, 3, 13, 5, 6, 10, 8): 9.698358901758564e-05,
 (16, 15, 3, 13, 5, 6, 10, 9): 0.00011519104086227357,
 (16, 15, 3, 13, 5, 11, 7, 8): 3.5283255832811005e-05,
 (16, 15, 3, 13, 5, 11, 7, 9): 4.190724436537834e-05,
 (16, 15, 3, 13, 5, 11, 10, 8): 3.338947347062841e-05,
 (16, 15, 3, 13, 5, 11, 10, 9): 3.9657928128722325e-05,
 (16, 15, 3, 13, 12, 6, 7, 8): 7.291473675554232e-05,
 (16, 15, 3, 13, 12, 6, 7, 9): 8.660356361473295e-05,
 (16, 15, 3, 13, 12, 6, 10, 8): 6.900113413720277e-05,
 (16, 15, 3, 13, 12, 6, 10, 9): 8.195523121443265e-05,
 (16, 15, 3, 13, 12, 11, 7, 8): 2.5103058086204466e-05,
 (16, 15, 3, 13, 12, 11, 7, 9): 2.9815842237511692e-05,
 (16, 15, 3, 13, 12, 11, 10, 8): 2.375568445192974e-05,
 (16, 15, 3, 13, 12, 11, 10, 9): 2.8215516110847653e-05,
 (16, 15, 14, 4, 5, 6, 7, 8): 9.569886784522287e-05,
 (16, 15, 14, 4, 5, 6, 7, 9): 0.00011366512941105437,
 (16, 15, 14, 4, 5, 6, 10, 8): 9.056235694994453e-05,
 (16, 15, 14, 4, 5, 6, 10, 9): 0.00010756430305041894,
 (16, 15, 14, 4, 5, 11, 7, 8): 3.294717014966156e-05,
 (16, 15, 14, 4, 5, 11, 7, 9): 3.9132587909463446e-05,
 (16, 15, 14, 4, 5, 11, 10, 8): 3.1178774114757226e-05,
 (16, 15, 14, 4, 5, 11, 10, 9): 3.7032197709628604e-05,
 (16, 15, 14, 4, 12, 6, 7, 8): 6.808709064962846e-05,
 (16, 15, 14, 4, 12, 6, 7, 9): 8.086958753189193e-05,
 (16, 15, 14, 4, 12, 6, 10, 8): 6.443260558805748e-05,
 (16, 15, 14, 4, 12, 6, 10, 9): 7.652901875812073e-05,
 (16, 15, 14, 4, 12, 11, 7, 8): 2.34409979045611e-05,
 (16, 15, 14, 4, 12, 11, 7, 9): 2.7841751113037808e-05,
 (16, 15, 14, 4, 12, 11, 10, 8): 2.2182833165060627e-05,
 (16, 15, 14, 4, 12, 11, 10, 9): 2.634738173170886e-05,
 (16, 15, 14, 13, 5, 6, 7, 8): 1.2253500133687925e-05,
 (16, 15, 14, 13, 5, 6, 7, 9): 1.4553941021398785e-05,
 (16, 15, 14, 13, 5, 6, 10, 8): 1.1595809626379331e-05,
 (16, 15, 14, 13, 5, 6, 10, 9): 1.377277737433705e-05,
 (16, 15, 14, 13, 5, 11, 7, 8): 4.218630407273619e-06,
 (16, 15, 14, 13, 5, 11, 7, 9): 5.010625328981898e-06,
 (16, 15, 14, 13, 5, 11, 10, 8): 3.992200967322881e-06,
 (16, 15, 14, 13, 5, 11, 10, 9): 4.741686603018088e-06,
 (16, 15, 14, 13, 12, 6, 7, 8): 8.718025543698125e-06,
 (16, 15, 14, 13, 12, 6, 7, 9): 1.035472544185162e-05,
 (16, 15, 14, 13, 12, 6, 10, 8): 8.250096986142511e-06,
 (16, 15, 14, 13, 12, 6, 10, 9): 9.79894916939134e-06,
 (16, 15, 14, 13, 12, 11, 7, 8): 3.0014385480700973e-06,
 (16, 15, 14, 13, 12, 11, 7, 9): 3.564920972079659e-06,
 (16, 15, 14, 13, 12, 11, 10, 8): 2.840340280652715e-06,
 (16, 15, 14, 13, 12, 11, 10, 9): 3.3735785264876293e-06}

In [ ]:
round1_results_for{key:val for key, val in myDict.items() if val != 42}